### ISSUE TITLE
define separate headless services for plugin metrics

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-charts#88]
In a [PR discussion](https://github.com/vapor-ware/synse-charts/pull/85#discussion_r435321487) for the Juniper JTI plugin, a suggestion was made to define a separate headless service for the metrics port, if metrics are enabled.

@lazypower - does this seem like a pattern that we should adopt for all plugins?

**Comment by lazypower** [comment]
I do think I agree with this mostly. 

If we're exposing application / plugin metrics - we'll want these to be isolated to internal cluster operations and the way i see it is we have two methods to accomplish this:

1)  Expose a different port / service combination for scraping these internal metrics so they dont get exposed via ingress.
2) Map the /metrics endpoint to a default/404 response, so if the extant application is exposed via ingress its not reachable by external third parties unless we explicitly surface and endpoint for them.

Now with regard to the synse plugins, I don't think these are mapped to the ingress tier, and its likely fine that they be available inter-cluster. If someone has compromised a pod in the kubernetes runtime, we've got a full security onion to build out from here to limit cross-talk. And I believe we have a lot of service-accounts available, which means they could use those credentials to abuse service discovery and then mum's the word, so a headless service does little to mitigate.

but it would however bifurcate the traffic, and that's not a bad thing.

I think we need to weight the effort of cleanup / engineering vs needs. and once we have that answer, we can decide on a pattern. Otherwise we're creating work for the sake of work without implementing the rest of the security controls.

- pod security policies
- network security policies
- TLS termination / client-certificates required to establish connections between services (same namespace / cross-namespace)

just to name the top three focuses off the top of my head.

End of the day, i'm not opposed, but its incomplete without the rest of the controls from a security perspective.

**Comment by lazypower** [comment]
This appears to have been mostly completed. are there any plugins left that aren't using an explicit monitoring service endpoint now?

**Comment by edaniszewski** [comment]
It looks like all the plugin charts in this repo have been updated to have a separate headless service for exporting metrics, so I think this can be closed. not sure if we want to open an issue here or somewhere else to track some of the longer-term work you mentioned in your comment about pod/network security policies, tls termination, etc

**Comment by lazypower** [comment]
We should file discrete issues for those. If we bring it up in weekly retro we can get some issues bombed out for it and maybe schedule between bigger task items this quarter / file for next.

**Comment by edaniszewski** [comment]
I think imma leave this issue open until those other discrete issues are filed just so we don't lose track of it.
